CUDA_VISIBLE_DEVICES=7 torchrun --nproc_per_node 1 --master_port 12340 main.py --cfg configs/vssm/vmambav0_tiny_224.yaml --data-path /media/Disk1/Dataset/ImageNet_ILSVRC2012 --output /tmp --pretrain /home/LiuYue/Workspace/PylanceAware/ckpts/ckpts/publish/vssm/classification/vssmtiny/vssmtiny_dp01_ckpt_epoch_292.pth --eval
CUDA_VISIBLE_DEVICES=7 torchrun --nproc_per_node 1 --master_port 12340 main.py --cfg configs/vssm/vmambav0_small_224.yaml --data-path /media/Disk1/Dataset/ImageNet_ILSVRC2012 --output /tmp --pretrain /home/LiuYue/Workspace/PylanceAware/ckpts/publish/vssm0/classification/vssm0_small/vssm0_small_ckpt_epoch_238.pth --eval
CUDA_VISIBLE_DEVICES=7 torchrun --nproc_per_node 1 --master_port 12340 main.py --cfg configs/vssm/vmambav0_base_224.yaml --data-path /media/Disk1/Dataset/ImageNet_ILSVRC2012 --output /tmp --pretrain /home/LiuYue/Workspace/PylanceAware/ckpts/publish/vssm0/classification/vssm0_base/vssm0_base_ckpt_epoch_241.pth --eval

CUDA_VISIBLE_DEVICES=7 torchrun --nproc_per_node 1 --master_port 12340 main.py --cfg configs/vssm/vmambav2_tiny_224.yaml --data-path /media/Disk1/Dataset/ImageNet_ILSVRC2012 --output /tmp --pretrain /home/LiuYue/Workspace/PylanceAware/ckpts/publish/vssm1/classification/vssm1_tiny_0230/vssm1_tiny_0230_ckpt_epoch_262.pth --eval
CUDA_VISIBLE_DEVICES=7 torchrun --nproc_per_node 1 --master_port 12340 main.py --cfg configs/vssm/vmambav2_small_224.yaml --data-path /media/Disk1/Dataset/ImageNet_ILSVRC2012 --output /tmp --pretrain /home/LiuYue/Workspace/PylanceAware/ckpts/publish/vssm1/classification/vssm1_small_0229/vssm1_small_0229_ckpt_epoch_222.pth --eval
CUDA_VISIBLE_DEVICES=7 torchrun --nproc_per_node 1 --master_port 12340 main.py --cfg configs/vssm/vmambav2_base_224.yaml --data-path /media/Disk1/Dataset/ImageNet_ILSVRC2012 --output /tmp --pretrain /home/LiuYue/Workspace/PylanceAware/ckpts/publish/vssm1/classification/vssm1_base_0229/vssm1_base_0229_ckpt_epoch_237.pth --eval

CUDA_VISIBLE_DEVICES=7 torchrun --nproc_per_node 1 --master_port 12340 main.py --cfg configs/vssm/vmambav2v_tiny_224.yaml --data-path /media/Disk1/Dataset/ImageNet_ILSVRC2012 --output /tmp --pretrain /home/LiuYue/Workspace/PylanceAware/ckpts/publish/vssm1/classification/vssm1_tiny_0230s/vssm1_tiny_0230s_ckpt_epoch_264.pth --eval
CUDA_VISIBLE_DEVICES=7 torchrun --nproc_per_node 1 --master_port 12340 main.py --cfg configs/vssm/vmambav2v_small_224.yaml --data-path /media/Disk1/Dataset/ImageNet_ILSVRC2012 --output /tmp --pretrain /home/LiuYue/Workspace/PylanceAware/ckpts/publish/vssm1/classification/vssm1_small_0229s/vssm1_small_0229s_ckpt_epoch_240.pth --eval
CUDA_VISIBLE_DEVICES=7 torchrun --nproc_per_node 1 --master_port 12340 main.py --cfg configs/vssm/vmambav2v_base_224.yaml --data-path /media/Disk1/Dataset/ImageNet_ILSVRC2012 --output /tmp --pretrain /home/LiuYue/Workspace/PylanceAware/ckpts/publish/vssm1/classification/vssm1_base_0229s/vssm1_base_0229s_ckpt_epoch_225.pth --eval


